# Generated by Django 2.1.2 on 2018-10-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_auto_20181030_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negativetweets',
            name='tweetText',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='positivetweets',
            name='tweetText',
            field=models.TextField(max_length=1000),
        ),
    ]
